name: elk
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - matplotlib
  - astropy
  - scipy
  - jupyter
  - jupyterlab
  - ipython
  - pandas
  - tqdm
  - h5py
  - pip:
    - lightkurve
    - tables